### ISSUE TITLE
About Network Architecture

### ISSUE THREAD

**Issue by ZJJTSL** [3dpose/GnTCN#1]
i wonder if u can share the details of network architecture of gcns and tcns, it's hard to understand the implementation according to the codes.

**Comment by 3dpose** [comment]
Please refer to the Graph Convolutional Layers and Temporal Convolutional Network sections in Supplementary Material for the details of network architecture of gcns and tcns, see page 10 in [the arXiv paper](https://arxiv.org/pdf/2012.11806v3.pdf).
