### ISSUE TITLE
Why to use  2D Ground-truth joints as input?

### ISSUE THREAD

**Issue by gurkirt** [3dpose/GnTCN#10]
Thanks for the code and your work?

Why do you use  2D ground-truth joints as input for evaluation? 
This is a lifting network not entirely 2D+3D pose estimation work like https://github.com/mks0601/3DMPPE_POSENET_RELEASE? Is that right?

Thanks
G.

**Comment by 3dpose** [comment]
Q: Why do you use 2D ground-truth joints as input for evaluation?
A: As stated in the [readme](https://github.com/3dpose/GnTCN#testing-on-wild-videos), to keep the repository simple, 2D joint estimator is not included in this repo, you can use off-the-shelf 2D pose estimator. Also as explained in the paper, HRNet was used. 2D ground-truth joints were provided to facilitate the code release. It helps to demonstrate the upper bound performance of the model, where the 2D ground-truth joints are used as input to mimic the situation there is no error in 2D joints estimation.

**Comment by 3dpose** [comment]
Q: This is a lifting network not entirely 2D+3D pose estimation work like https://github.com/mks0601/3DMPPE_POSENET_RELEASE? Is that right?
A: A lifting network usually estimates a 3D pose based on a 2D pose from a single image. Our method is a monocular video method, which means it takes sequence (temporal window) of 2D poses as input to estimate the 3D pose center frame. As explained in last answer, you can use off-the-shelf 2D pose estimators to get estimated 2D joints. To make it easy to reproduce our results (Table 3) reported in the paper, we also provided the estimated 2D joints that can be [downloaded along with the pre-trained models](https://github.com/3dpose/GnTCN#pre-trained-model).

**Comment by gurkirt** [comment]
Thanks a lot for your answers, it helps a lot.
Many thanks
Gurkirt
