### ISSUE TITLE
The confidence scores of the part affinity field for bone-GCN

### ISSUE THREAD

**Issue by ericwang0701** [3dpose/GnTCN#2]
Thank you for sharing such amazing work. I have gone through the code and I have a question about how to get the confidence scores of the PAF for bone-GCN.

In the current `eval_gt_h36m.py`, I understand that we assume the confidence score of each joint is 1 in this case. So we get the 
`affpts = torch.ones(bsize,17,17).cuda() / 17`. If we want to test our own custom images, we should use the real confidence scores of each joint from OpenPose.

However, when I looked at the outputs data from OpenPose, I couldn't find where we can get the confidence scores of the PAF. I assume this part: `affb = torch.ones(bsize,16,16).cuda() / 16` is where we should put the actually scores. It would be great if you can share details about how to generate the confidence scores of the PAF. 

Thank you so much for your time and help.

**Comment by ddddwee1** [comment]
The confidence score of PAF is the cosine similarity between PAF and the vector and the bone vector. 
You can refer to the following implementation:
https://github.com/spmallick/learnopencv/blob/bac974ac5043c387d5de1a8736e9c94719876bee/OpenPose-Multi-Person/multi-person-openpose.py#L111

**Comment by ericwang0701** [comment]
Thank you so much for your reply. Now I know how to compute the confidence score of PAF. But I'm still confused about the shape of affpts and affb. For each joint and bone,  we get a confidence score, I'd like to know why the shape of affpts is (bsize,17,17) instead of (bsize,17,1).

Thank you so much for your time and help.

**Comment by ddddwee1** [comment]
The shape of confidence score should be (bsize, 1, 17) for affpts and (bsize, 1, 16) for boneaff, and you need to repeat it into shape (bsize, 17, 17) and (bsize, 16,16), respectively.

**Comment by ericwang0701** [comment]
Thank you so much for your reply. I'd like to make sure that I understand it correctly, The shape of confidence score for **all joints** is (bsize, 1, 17), but we want to make the shape to be (bsize, 17, 17). So we just repeat it into shape (bsize, 17, 17)?

**Comment by ddddwee1** [comment]
After repeating it into shape (bsize, 17, 17), you may also need to multiply it with the exponential term as described in equation 1 in the paper. For example, for the entry (bsize, i, j), you need to multiply it by exp(-order(i,j)). The order is the number of hops required to reach joint i from joint j. 
You can try either adding it or not adding it.
