### ISSUE TITLE
Questions about "points_eval.pkl"

### ISSUE THREAD

**Issue by ericwang0701** [3dpose/GnTCN#3]
Thank you again for sharing your amazing work. I'd like to know whether it's possible to share the `points_eval.pkl `file. More specifically, I'd like to know the format of the p2d and p3d (i.e. `p2d,p3d = dataset[i])`. Is there any preprocessing for the 2d joint data (e.g. normalize to 0-1,  relative to root joint.. etc )? 

I have been tried to use GnTCN on a custom image these days, but there are some parts that still need your guidance or clarification. Let me know if it's ok to email you to discuss more instead of posting issues here. 

Thank you so much for your help and time.

**Comment by ddddwee1** [comment]
The points are normalized to 0~1. The way we do for H36M is to divide the 2D coordinates by 1000 (the height and width of the video). 

For further discussion, you can email me via chengyu996@gmail.com
