### ISSUE TITLE
RooTTCN Details

### ISSUE THREAD

**Issue by amek-aymen** [3dpose/GnTCN#5]
Thanks for sharing your amazing work. 
I read in your paper that you are using the rootTCN model to get the absolute poses, I have some questions about that:

1- Actually, I tried to load the pre-trained model from the /ckpts/model_root folder using the Discriminator2D class as follows:

`roottcn = networktcn.Discriminator2D()
M.Saver(roottcn).restore ('./ckpts/model_root/')`

However, I'm getting this error:
![image](https://user-images.githubusercontent.com/66665382/108220264-d6bfd180-7136-11eb-9733-8df239956057.png)

Is there a problem in the network or I have loaded it incorrectly. Also, I would like to know the size of the input, by visualising the pth model I see it is a size of (1024,34,3) and according to the paper the input is 2D poses of each person but in fact the Discriminator2D class doesn't need any parameters.. Could you, please, help me with this issue.

2- My second question is about the data format used to train this model to estimate Z/f. Did you use intrinsic parameters and poses given in Human3.6m for that?

Thank you in advance for your time.

**Comment by ddddwee1** [comment]
Hi, we have updated the codes and hope the updated codes can clarify your questions.
