### ISSUE TITLE
3D coordinate for human pose

### ISSUE THREAD

**Issue by r-matsuzaka** [3dpose/GnTCN#7]
Thank you very much for sharing your great work.
I want to infer 3D human pose by giving new image or movie as an input using GnTCN. Is it possible in this repo?
I have limited knowledge about this technology. Sorry for basic question in advance.

**Comment by 3dpose** [comment]
Thank you for your interest. To keep this repository simple we didn't include 2D pose estimator, you can use off-the-shelf 2D pose estimation methods to get 2D joints first, and then you can use the code from this repository to infer 3D human pose on testing videos (the TCN takes multiple frames as input). In particular, as stated in the paper: we use the original implementation of HRNet (Sunet al. 2019a) as the 2D pose estimator and extract PAF from original OpenPose (Cao et al. 2019).

**Comment by r-matsuzaka** [comment]
Thank you very much for your quick response and gentle advice!
I am trying to challenge it!

**Comment by ryo-matsuzaka** [comment]
Hello. Thank you for last Saturday.
I think this issue can be closed because my clarification is done.
